# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-09 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antropometrico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.IntegerField(blank=1, default='0')),
                ('porcentaje_grasa', models.IntegerField(blank=1, default='0')),
                ('observacion', models.TextField(blank=1, null=1)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=1, null=1)),
                ('estatura', models.IntegerField(blank=1, default='0')),
                ('peso', models.IntegerField(blank=1, default='0')),
                ('edad', models.IntegerField(blank=1, default='0')),
                ('pa', models.CharField(blank=1, max_length=10, null=1)),
                ('fc', models.IntegerField(blank=1, default='0')),
                ('fr', models.IntegerField(blank=1, default='0')),
                ('t_oral', models.IntegerField(blank=1, default='0')),
                ('t_rectal', models.IntegerField(blank=1, default='0')),
                ('tratamiento', models.TextField(blank=1, null=1)),
            ],
        ),
        migrations.CreateModel(
            name='IMC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.IntegerField(blank=1, default='0')),
                ('estatura', models.IntegerField(blank=1, default='0')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cineantro.Examen')),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=1, max_length=50, null=1)),
                ('direccion', models.CharField(blank=1, max_length=50, null=1)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=1, max_length=50, null=1)),
                ('apellidos', models.CharField(blank=1, max_length=50, null=1)),
                ('f_nac', models.DateField(blank=1, null=1)),
                ('sexo', models.IntegerField(blank=1, choices=[(1, 'Masculino'), (2, 'Femenino')], default='1')),
                ('domicilio', models.CharField(blank=1, max_length=50, null=1)),
                ('tel', models.IntegerField(blank=1, default='0')),
                ('ci', models.IntegerField(blank=1, default='0')),
                ('seguro', models.CharField(blank=1, max_length=50, null=1)),
                ('procedencia', models.CharField(blank=1, max_length=50, null=1)),
                ('ocupacion', models.CharField(blank=1, max_length=50, null=1)),
                ('ec', models.IntegerField(blank=1, choices=[(1, 'Soltero'), (2, 'Casado'), (3, 'Divorciado'), (4, 'Viudo')], default='1')),
                ('enfermedad', models.CharField(blank=1, max_length=50, null=1)),
                ('sintomas', models.CharField(blank=1, max_length=50, null=1)),
                ('signos', models.CharField(blank=1, max_length=50, null=1)),
                ('sindromes', models.CharField(blank=1, max_length=50, null=1)),
                ('a_personales', models.CharField(blank=1, max_length=50, null=1)),
                ('a_patologicos', models.CharField(blank=1, max_length=50, null=1)),
                ('a_nopatologicos', models.CharField(blank=1, max_length=50, null=1)),
                ('a_hereditarios', models.CharField(blank=1, max_length=50, null=1)),
                ('a_presuntivo', models.CharField(blank=1, max_length=50, null=1)),
                ('d_definitivo', models.CharField(blank=1, max_length=50, null=1)),
                ('interconsulta', models.CharField(blank=1, max_length=50, null=1)),
                ('imagen', models.ImageField(blank=1, null=1, upload_to=b'')),
                ('institucion', models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='cineantro.Institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Porcentaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_grasa_deseado', models.IntegerField(blank=1, default='0')),
                ('antropometrico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cineantro.Antropometrico')),
            ],
        ),
        migrations.AddField(
            model_name='examen',
            name='pacientes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cineantro.Paciente'),
        ),
        migrations.AddField(
            model_name='antropometrico',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cineantro.Examen'),
        ),
    ]
